export const AuthTypes = {
    SET_USER_DATA: 'SET_USER_DATA',
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    CHECK_LOGIN: 'CHECK_LOGIN',
    INITIALIZED_SUCCESS: 'INITIALIZED_SUCCESS',
    GET_CAPTCHA_URL_SUCCESS: 'GET_CAPTCHA_URL_SUCCESS',
}
