export const ProfileTypes = {
    SET_USER_PROFILE: 'SET_USER_PROFILE',
    GET_USER_STATUS: 'GET_USER_STATUS',
    UPDATE_USER_INFO: 'UPDATE_USER_INFO',
    UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
    UPDATE_USER_PHOTO: 'UPDATE_USER_PHOTO',
}
